// TODO: is there a recommended warm-up period for the sensor? sen66 by sensirion (for gas sensors, usually a 24-48 hour "burn in", then still a few minutes for each use thereafter)

//logging to microSD card -- done
//led cannot be used at the same time with sd card, but sd card system seems stable enough to not need physical feedback
//can read timeestamp with wifi yayay

/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * Generator:     sensirion-driver-generator 1.1.2
 * Product:       sen66
 * Model-Version: 1.6.0
 */
/*
 * Copyright (c) 2025, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */
#include <Arduino.h>
#include <SensirionI2cSen66.h>
#include <Wire.h>

//for wifi
#include <WiFi.h>
#include "time.h"

// Libraries for the xiao sense sd card 
#include "FS.h"
#include "SPI.h"
#include "SD.h"

//wifi config, can only operate on 2.4 gHz
const char* ssid = "";  
const char* password = "";  
const char* ntpServer = "pool.ntp.org";

// eastern time
const long  gmtOffset_sec = -18000; 
const int   daylightOffset_sec = 3600;

//SD pinout
const int SD_CS_PIN = D2;

// macro definitions
// make sure that we use the proper definition of NO_ERROR
#ifdef NO_ERROR
#undef NO_ERROR
#endif
#define NO_ERROR 0

SensirionI2cSen66 sensor;

static char errorMessage[64];
static int16_t error;

//buffer for file name
char currentFilename[32];

int num_data_error = 0;

void sd_error(bool error){
  while(true){
    digitalWrite(21, HIGH);
    //turn off led if sd stopped working
  }
}

// get time
String getTimestamp() {
  struct tm timeinfo;
  if(!getLocalTime(&timeinfo)){
    return String(millis()); // safety
  }
  char timeStrBuff[50];
  strftime(timeStrBuff, sizeof(timeStrBuff), "%Y-%m-%d %H:%M:%S", &timeinfo);
  return String(timeStrBuff);
  //return timestamp as string
}

//generate filename
void generateFileName() {
  struct tm timeinfo;
  if(!getLocalTime(&timeinfo)){
      Serial.println("Real-time sync failed, using numbered filename");
      int file_i = 0;
      while (true) {
          sprintf(currentFilename, "/data_%d.csv", file_i);
          if (!SD.exists(currentFilename)) break; //fallback
          file_i++;
      }
      return;
  }
  strftime(currentFilename, sizeof(currentFilename), "/%m-%d_%H-%M.csv", &timeinfo);
}

void setup() {

    pinMode(21, OUTPUT);
    digitalWrite(21, HIGH);
    delay(500);
    digitalWrite(21, LOW);

    Serial.begin(115200);

    //wifi setup
    Serial.println("Connecting to WiFi");
    WiFi.begin(ssid, password);
    
    int retry_count = 0;
    // try connecting for 20 seconds
    while (WiFi.status() != WL_CONNECTED && retry_count < 40) {
        delay(500);
        Serial.print(".");
        retry_count++;
    }

    if (WiFi.status() == WL_CONNECTED) {
        Serial.println("\nWifi Connected!");
        configTime(gmtOffset_sec, daylightOffset_sec, ntpServer);
        
        // wait for time to update
        struct tm timeinfo;
        retry_count = 0;
        while(!getLocalTime(&timeinfo) && retry_count < 20){
            Serial.println("Waiting for time sync...");
            delay(500);
            retry_count++;
        }
        if(getLocalTime(&timeinfo)) {
           Serial.println("Time Synced! " + getTimestamp());
        }
        
        // TODO: save power if needed?
        // WiFi.disconnect(true); 
        // WiFi.mode(WIFI_OFF);
    } else {
        Serial.println("WiFi Failed. Preceeding with fallback millis.");
    }

    //SD card init
    if (!SD.begin(SD_CS_PIN)) {
        Serial.println("Card Mount Failed! Check wiring and D2 pin.");
        sd_error(true);
    }
    
    uint8_t cardType = SD.cardType();
    if (cardType == CARD_NONE) {
        Serial.println("No SD card attached");
        sd_error(true);
    }
    Serial.println("SD Card Initialized.");

    // Filename autogeneration
    generateFileName();
    
    Serial.print("Logging to: ");
    Serial.println(currentFilename);

    // create file, make header
    File file = SD.open(currentFilename, FILE_WRITE);
    if (!file) {
        Serial.println("Failed to create file");
        sd_error(true);
    }
    file.println("Time(ms),PM1.0,PM2.5,PM4.0,PM10.0,Humidity,Temp,VOC,NOx,CO2");
    file.close();

    Wire.begin();
    sensor.begin(Wire, SEN66_I2C_ADDR_6B);

    error = sensor.deviceReset();
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute deviceReset(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    delay(1200); 

    int8_t serialNumber[32] = {0};
    error = sensor.getSerialNumber(serialNumber, 32);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute getSerialNumber(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
    Serial.print("serialNumber: ");
    Serial.print((const char*)serialNumber);
    Serial.println();
    error = sensor.startContinuousMeasurement();
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute startContinuousMeasurement(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }
}

void loop() {

    float massConcentrationPm1p0 = 0.0;
    float massConcentrationPm2p5 = 0.0;
    float massConcentrationPm4p0 = 0.0;
    float massConcentrationPm10p0 = 0.0;
    float humidity = 0.0;
    float temperature = 0.0;
    float vocIndex = 0.0;
    float noxIndex = 0.0;
    uint16_t co2 = 0;
    delay(1000);
    error = sensor.readMeasuredValues(
        massConcentrationPm1p0, massConcentrationPm2p5, massConcentrationPm4p0,
        massConcentrationPm10p0, humidity, temperature, vocIndex, noxIndex,
        co2);
    if (error != NO_ERROR) {
        Serial.print("Error trying to execute readMeasuredValues(): ");
        errorToString(error, errorMessage, sizeof errorMessage);
        Serial.println(errorMessage);
        return;
    }

    /*
    Serial.print("massConcentrationPm1p0: ");
    Serial.print(massConcentrationPm1p0);
    Serial.print("\t");
    Serial.print("massConcentrationPm2p5: ");
    Serial.print(massConcentrationPm2p5);
    Serial.print("\t");
    Serial.print("massConcentrationPm4p0: ");
    Serial.print(massConcentrationPm4p0);
    Serial.print("\t");
    Serial.print("massConcentrationPm10p0: ");
    Serial.print(massConcentrationPm10p0);
    Serial.print("\t");
    Serial.print("humidity: ");
    Serial.print(humidity);
    Serial.print("\t");
    Serial.print("temperature: ");
    Serial.print(temperature);
    Serial.print("\t");
    Serial.print("vocIndex: ");
    Serial.print(vocIndex);
    Serial.print("\t");
    Serial.print("noxIndex: ");
    Serial.print(noxIndex);
    Serial.print("\t");
    Serial.print("co2: ");
    Serial.print(co2);
    Serial.println();
    */

    //log info to sd
    File file = SD.open(currentFilename, FILE_APPEND);
    if (!file) {
        Serial.println("Failed to append to file");
        num_data_error++;
        if (num_data_error > 10){
          sd_error(true);
        }
        
    } else {
        // Write CSV formatted line
        file.print(getTimestamp()); 
        file.print(",");
        file.print(massConcentrationPm1p0);
        file.print(",");
        file.print(massConcentrationPm2p5);
        Serial.println(massConcentrationPm2p5);
        file.print(",");
        file.print(massConcentrationPm4p0);
        file.print(",");
        file.print(massConcentrationPm10p0);
        file.print(",");
        file.print(humidity);
        file.print(",");
        file.print(temperature);
        Serial.println(temperature);
        file.print(",");
        file.print(vocIndex);
        Serial.println(vocIndex);
        file.print(",");
        file.print(noxIndex);
        file.print(",");
        file.println(co2);
        
        file.close();
    }
}
